### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by whybfq** [YuxinWenRick/diffusion_memorization#3]
1. Detect memorization
You may first download the memorized prompts dataset from this link and unzip it.

(May I ask where is the link, it seems no in the page), 

2. and in the det_mem_viz.ipynb, 
nonmem_data = list(read_jsonlines(f"det_outputs/non_memorized_prompts.jsonl"))

may I ask where is this data file from, thanks

**Comment by YuxinWenRick** [comment]
Hi sorry for the confusion.
1. Actually the dataset is already [here](https://github.com/YuxinWenRick/diffusion_memorization/blob/main/examples/sdv1_500_memorized.jsonl). You don't have to download it.
2. This file will be generated after running: `python detect_mem.py --run_name memorized_prompts --dataset examples/sdv1_500_memorized.jsonl --end 500 --gen_seed 0`

Please let me know if you have further questions!

**Comment by whybfq** [comment]
Thanks a lot.
